import "./styles/globals.css"

export const metadata = {
  title: "dashboard",
  description: "Generated by aliasghar gholami",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="2xl:max-w-[2200px]">{children}</main>
      </body>
    </html>
  )
}
