"use client"

import './../styles/globals.css'
import Link from "next/link"
import Image from 'next/image';
import { RiDashboard2Line } from "react-icons/ri";
import { IoMdMenu } from "react-icons/io";
import { MdLaptop } from "react-icons/md";
import { MdOutlineFormatListBulleted } from "react-icons/md";
import { BsTable } from "react-icons/bs";
import { FaChartColumn } from "react-icons/fa6";
import { RiContactsBook2Fill } from "react-icons/ri";
import { MdSecurity } from "react-icons/md";
import { IoDocumentOutline } from "react-icons/io5";



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section className='w-full flex flex-wrap'>
      {/* Include shared UI here e.g. a header or sidebar */}
      <div className='w-[15%] hidden xl:block bg-[#191c24] min-h-screen text-white'>
        <h2 className='pt-5 text-2xl text-center'>dashboard</h2>
        <figure className='flex my-5 justify-start items-center gap-x-3'>
          <Image src='/5.jpg' alt='me' width='64' height='64' className='rounded-full' />
          <figcaption>
            <h1 className='capitalize'>aliasghar gholami</h1>
            <p className='text-slate-500 text-xs'>Software Developer</p>
          </figcaption>
        </figure>
        <p className='text-slate-500 m-2'>Navigation</p>
        <ul className='flex flex-wrap justify-center gap-3 *:w-full'>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/'}><RiDashboard2Line /><span className='px-2'> dashboard</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/basic'}><MdLaptop /><span className='px-2'> basic ui elements</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/soon'}><MdOutlineFormatListBulleted /><span className='px-2'>form elements</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/tables'}><BsTable /><span className='px-2'>tables</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/chart'}><FaChartColumn /><span className='px-2'>charts</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/soon'}><RiContactsBook2Fill /><span className='px-2'>icons</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/soon'}><MdSecurity /><span className='px-2'>user pages</span></Link></li>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/soon'}><IoDocumentOutline /><span className='px-2'>documentation</span></Link></li>

        </ul>
      </div>
      <header className='xl:w-[85%] absolute right-0 w-full flex items-center *:mx-5 bg-[#191c24] h-14 text-white'>
        <button className='hover:bg-black p-3 rounded-full'><IoMdMenu /></button>
        <input type="text" placeholder='search products' className='bg-transparent w-1/3 p-2 border text-slate-500' />
        <figure className='flex my-5 w-1/2 justify-end items-center gap-x-3'>
          <Image src='/5.jpg' alt='me' width='44' height='44' className='rounded-full' />
          <figcaption>
            <h1 className='capitalize'>aliasghar gholami</h1>
          </figcaption>
        </figure>
      </header>
      <div className='w-[85%] bg-black mt-14'>
        {children}
      </div>
    </section>
  )
}